apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    app.kubernetes.io/managed-by: cpg
  name: cpg-exit-node-vpn-exit-node-base
  namespace: exit-node-base
spec:
  egress:
  # UDP/443, UDP/5351 to entity host
  - toEntities:
    - host
    toPorts:
    - ports:
      - port: "443"
        protocol: UDP
      - port: "5351"
        protocol: UDP
  # UDP/1900 to io.kubernetes.pod.namespace=
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: ""
    toPorts:
    - ports:
      - port: "1900"
        protocol: UDP
  endpointSelector:
    matchLabels:
      app: exit-node-vpn-exit-node-base
status: {}
