apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    app.kubernetes.io/managed-by: cpg
  name: cpg-exit-node-vpn-exit-node-base
  namespace: exit-node-base
spec:
  egress:
  # UDP/53 to io.kubernetes.pod.namespace=kube-system, k8s-app=kube-dns
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP
  # TCP/8200 to app.kubernetes.io/name=vault, io.kubernetes.pod.namespace=vault
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: vault
        io.kubernetes.pod.namespace: vault
    toPorts:
    - ports:
      - port: "8200"
        protocol: TCP
  endpointSelector:
    matchLabels:
      app: exit-node-vpn-exit-node-base
status: {}
