containers:
  - name: main
    image: node:22-bookworm
    resources:
      requests:
        cpu: "500m"
        memory: 512Mi
      limits:
        cpu: "2"
        memory: 2Gi
        ephemeral-storage: 10Gi
    volumeMounts:
      - name: vault-tls
        mountPath: /vault-tls
        readOnly: true

volumes:
  - name: vault-tls
    secret:
      secretName: vault-tls
restartPolicy: Never
