{{- if .Values.ingress.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: '{{ .Values.repo }}'
    path: '1.argo/helm/auth'
    helm:
      releaseName: auth
      valuesObject:
        traefik:
          ips: "{{ .Values.traefik.ips }}"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'kaniop'
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
{{- end -}}
