{{- if .Values.external.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: 'https://git.batleforc.fr/batleforc/weebo5GitOpsInternal'
    path: '1.app'
    helm:
      releaseName: external
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'argocd'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
{{- end -}}
