{{- if .Values.dns.enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.dns.ns }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-{{ .Values.dns.ns }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: '{{ .Values.repo }}'
    path: '1.argo/helm/dns'
    helm:
      releaseName: in-{{ .Values.dns.ns }}
      valuesObject:
        annotations:
          lbipam.cilium.io/sharing-key: "weebo-gate"
          lbipam.cilium.io/ips: "{{ .Values.traefik.ips }}"
          lbipam.cilium.io/sharing-cross-namespace: "*"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: '{{ .Values.dns.ns }}'
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
{{- end -}}
