repo: ""

netbird:
  enabled: true
  domain: vpn.batleforc.fr
  dashboard:
    version: "v2.90.9"
  server:
    version: "0.76.1"

traefik:
  ips: ""

exitNode:
  - name: exit-node-base
    enabled: true
    namespace: exit-node-base
