repo: ""

netbird:
  enabled: true
  domain: vpn.batleforc.fr
  dashboard:
    version: "v2.39.0"
  server:
    version: "0.72.4"

traefik:
  ips: ""

exitNode:
  - name: exit-node-base
    enabled: true
    namespace: exit-node-base
