{{- if .Values.managementTokenSecretJob.enabled -}}
{{- if .Values.managementTokenSecretJob.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netbird.managementTokenSecretJob.serviceAccountName" . }}
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.managementTokenSecretJob.labels" . | nindent 4 }}
  {{- with .Values.managementTokenSecretJob.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.managementTokenSecretJob.serviceAccount.roleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "netbird.managementTokenSecretJob.roleBindingName" . }}
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.managementTokenSecretJob.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "netbird.managementTokenSecretJob.serviceAccountName" . }}
    namespace: {{ include "netbird.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "netbird.managementTokenSecretJob.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- if .Values.managementTokenSecretJob.serviceAccount.role.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "netbird.managementTokenSecretJob.roleName" . }}
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.managementTokenSecretJob.labels" . | nindent 4 }}
rules:
  # Allow to read/write secrets in the namespace
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch", "delete"]
  # Allow to exec into the management pod to retrieve the token
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
{{- end }}
{{- end }}
