{{- if .Values.gitPages.enabled -}}
# https://git-pages.org/running-a-server/#wildcard-domains
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-pages
  labels:
    app: git-pages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-pages
  template:
    metadata:
      labels:
        app: git-pages
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
        vault.security.banzaicloud.io/vault-role: "auth-read"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        vault.security.banzaicloud.io/vault-agent: "false"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
    spec:
      containers:
        - name: git-pages
          image: codeberg.org/git-pages/git-pages:latest
          ports:
            - containerPort: 3000
          command: ["git-pages"]
          args: ["--config", "/etc/git-pages/config.toml"]
          env:
            - name: PAGES_STORAGE_TYPE
              value: s3
            - name: PAGES_STORAGE_S3_ENDPOINT
              value: "vault:mv/data/{{ .Release.Namespace }}/s3#url"
            - name: PAGES_STORAGE_S3_ACCESS_KEY_ID
              value: "vault:mv/data/{{ .Release.Namespace }}/s3#access_key"
            - name: PAGES_STORAGE_S3_SECRET_ACCESS_KEY
              value: "vault:mv/data/{{ .Release.Namespace }}/s3#secret_key"
            - name: PAGES_STORAGE_S3_BUCKET
              value: git-pages
            {{- range $key, $value := .Values.gitPages.env }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          resources:
            {{- toYaml .Values.gitPages.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/git-pages
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: git-pages-config
{{- end -}}
