{{- if .Values.gitPages.enabled -}}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: git-pages-https
  labels:
    argocd.argoproj.io/instance: git-pages
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: HostRegexp(`^.+{{ .Values.gitPages.dnsWildcardDomain.domain | replace "." "\\." }}$`)
      priority: 1
      services:
        - name: git-pages
          namespace: "{{ .Release.Namespace }}"
          passHostHeader: true
          port: 3000
      {{ if .Values.gitPages.middleware.strictSource.enabled }}
      middlewares:
      - name: vpn-only
        namespace: traefik
      {{ end }}
    {{- range .Values.gitPages.publicUrl }}
    {{- if .enabled }}
    - kind: Rule
      match: Host(`{{ .url | replace "https://" "" | replace "http://" "" }}`) {{ if .pathPrefix }} && PathPrefix(`{{ .pathPrefix }}`) {{ end }} && (Method(`GET`) || Method(`HEAD`) || Method(`OPTIONS`))
      priority: 2
      services:
        - name: git-pages
          namespace: "{{ $.Release.Namespace }}"
          passHostHeader: true
          port: 3000
    {{- end }}
    {{- end }}
  tls:
    secretName: "{{ .Values.gitPages.dnsWildcardDomain.certificateName }}"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: git-pages-http
  labels:
    argocd.argoproj.io/instance: git-pages
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: HostRegexp(`^.+{{ .Values.gitPages.dnsWildcardDomain.domain | replace "." "\\." }}$`)
      priority: 1
      services:
        - name: git-pages
          namespace: "{{ .Release.Namespace }}"
          passHostHeader: true
          port: 3000
      {{ if and .Values.gitPages.middleware.enabled .Values.gitPages.middleware.redirectToHttps.enabled }}
      middlewares:
      - name: redirect-to-https
        namespace: traefik
      {{- end }}
{{- end -}}
