version: "3"

dotenv:
  - .env
  - .env.global

includes:
  pulumi: 0.pulumi/Taskfile.yaml
  pulumi-conf: 0.pulumi-conf/Taskfile.yaml
  argo: .task/argo.yaml
  vault: .task/vault.yaml
  for-action: .task/fogejo-action.yaml

tasks:
  init:
    desc: "Initialize the project"
    silent: true
    cmds:
      - cog install-hook -a -o
      - mkdir -p .tmp
      - krew install cilium-policy-gen
      - mise upgrade
  recu:
    desc: "Run pre-commit hooks on all files, including submodules"
    cmds:
      - gitleaks git --pre-commit --redact --staged --verbose
  talosctl:
    desc: "Run talosctl commands on the cluster"
    silent: true
    env:
      TALOSCONFIG: 0.config/talosconfig.yaml
    cmds:
      - talosctl {{ .CLI_ARGS }}
  k:
    desc: "Run kubectl commands on the cluster"
    silent: true
    env:
      KUBECONFIG: 0.config/kubeconfig.yaml
    cmds:
      - kubectl {{ .CLI_ARGS }}
  k9s:
    desc: "Run k9s on the cluster"
    silent: true
    env:
      KUBECONFIG: 0.config/kubeconfig.yaml
    cmds:
      - k9s {{ .CLI_ARGS }}
  cilium:
    desc: "Run cilium-cli commands on the cluster"
    silent: true
    env:
      KUBECONFIG: 0.config/kubeconfig.yaml
    cmds:
      - cilium {{ .CLI_ARGS }}
  cpg:
    desc: "Run cilium-policy-gen commands on the cluster"
    silent: true
    env:
      KUBECONFIG: 0.config/kubeconfig.yaml
    cmds:
      - kubectl cilium-policy-gen {{ .CLI_ARGS }}
