{{- if .Values.kanidm.enabled -}}
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: admins
  namespace: {{ .Release.Namespace }}
spec:
  kanidmRef:
    name: {{ .Values.kaniop.instanceName }}
  entryManagedBy: batleforc
  members:
    - batleforc
  groupAttributes:
    displayname: Admins
    mail:
    - admins@{{ .Values.dns.domain }}

{{- end -}}
