{{- if .Values.kaniop.enabled -}}
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: admins
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  kanidmRef:
    name: {{ .Values.kaniop.instanceName }}
  entryManagedBy: batleforc
  members:
    - batleforc
  mail:
    - admins@{{ .Values.dns.domain }}

{{- end -}}
