{{- if .Values.kaniop.enabled -}}

apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Values.kaniop.instanceName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`{{ .Values.dns.domain }}`)
    priority: 10
    services:
    - name: {{ .Values.kaniop.instanceName }}
      port: 8443

  tls:
    secretName: {{ .Values.dns.certificate.name }}
    passthrough: true
{{- end -}}
