{{- if .Values.kanidm.enabled -}}
apiVersion: kaniop.rs/v1beta1
kind: KanidmPersonAccount
metadata:
  name: batleforc
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  kanidmRef:
    name: {{ .Values.kaniop.instanceName }}
  personAttributes:
    displayname: Balteforc
    mail:
    - max@batleforc.fr


{{- end -}}
