blocky:
  enabled: true
  image:
    repository: "ghcr.io/0xerr0r/blocky"
    tag: "v0.29.0"
  service:
    type: ClusterIP
    ipFamily: RequireDualStack
    annotations: {}
    clusterIP: 10.96.0.11
    port:
      - port: 53
        targetPort: 53
        protocol: UDP
        name: dns-udp
      - port: 53
        targetPort: 53
        protocol: TCP
        name: dns-tcp
      - port: 4000
        targetPort: 4000
        protocol: TCP
        name: web
      - port: 853
        targetPort: 853
        protocol: TCP
        name: dns-tls
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  config:
    upstreams:
      init:
        # Configure startup behavior.
        # accepted: blocking, failOnError, fast
        # default: blocking
        strategy: fast
      groups:
        default:
          - 1.1.1.1
          - 9.9.9.9
          - 2620:fe::fe
    strategy: parallel_best
    blocking:
      denylists:
        ads:
          - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
          - https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
          - https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
    prometheus:
      # enabled if true
      enable: true
      # url path, optional (default '/metrics')
      path: /metrics
