{{- if .Values.runner.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo-runner
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: forgejo-runner
  template:
    metadata:
      labels:
        app: forgejo-runner
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
        vault.security.banzaicloud.io/vault-role: "forgejo-readwrite"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
    spec:
      serviceAccountName: forgejo-runner
      imagePullSecrets:
        - name: docker-config
      containers:
        - name: runner
          image: {{ .Values.runner.image.repository }}:{{ .Values.runner.image.tag }}
          #args: ["forgejo-runner", "--config", "/config/config.yaml", "daemon"]
          command: ["/bin/sh", "-c"]
          args:
            - rsubst < /source-config/config.yaml > /config/config.yaml
            {{ range .Values.runner.podSpecToInclude }}
            - cp /source-config/podspec-{{ . }} /config/podspec-{{ . }}
            {{ end }}
            - forgejo-runner --config /config/config.yaml daemon
          volumeMounts:
            - name: target-config
              mountPath: /config
            - name: config
              mountPath: /source-config
              readOnly: true
          env:
            - name: RUNNER_TOKEN
              value: vault:mv/data/{{ $.Release.Namespace }}/sub#token
            - name: RUNNER_UUID
              value: vault:mv/data/{{ $.Release.Namespace }}/sub#uuid
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
      volumes:
        - name: target-config
          emptyDir: {}
        - name: config
          configMap:
            name: runner-config
{{- end -}}
