{{- if .Values.secretStore.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.runner.forgejo.existingSecret }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: store
    kind: SecretStore
  target:
    name: {{ .Values.runner.forgejo.existingSecret }}
  data:
    - secretKey: token
      remoteRef:
        key: mv/{{ $.Release.Namespace }}/sub
        property: token
    - secretKey: uuid
      remoteRef:
        key: mv/{{ $.Release.Namespace }}/sub
        property: uuid
{{- end -}}
