zone:
  "db.batleforc":
    zone: "batleforc.fr."
    file: |
      $TTL 1h ;
      $ORIGIN batleforc.fr.
      @       IN      SOA     maxleriche.net. maxleriche\.60.gmail.com. (
                              2024011944; serial
                              7200; refresh
                              3600; retry
                              1209600; expire
                              38400 ) ; minimum
      @                   IN      NS                  batleforc.fr.
      @                   IN      NS                  ns3082912.ip-94-23-38.eu.
      @                   3600    CAA       0  issue "letsencrypt.org"
      ns1                 IN      A                   94.23.38.81
      ns1                 IN      AAAA                2001:41d0:2:2751::1
      ns2                 IN      A                   94.23.38.81
      ns2                 IN      AAAA                2001:41d0:2:2751::2
      batleforc.fr.       3600    A                   94.23.38.81
      batleforc.fr.       3600    AAAA                2001:41d0:2:2751::1
      argo                3600    A                   94.23.38.81
      argo                3600    AAAA                2001:41d0:2:2751::1
      ns                  3600    A                   94.23.38.81
      ns                  3600    AAAA                2001:41d0:2:2751::1
      auth                3600    A                   94.23.38.81
      auth                3600    AAAA                2001:41d0:2:2751::1
      vpn                 3600    A                   94.23.38.81
      vpn                 3600    AAAA                2001:41d0:2:2751::1
      track               3600    A                   94.23.38.81
      track               3600    AAAA                2001:41d0:2:2751::1

  "db.maxleriche.net":
    zone: "maxleriche.net."
    file: |
      $TTL 1h;
      $origin maxleriche.net.
      @       IN      SOA     batleforc.fr. maxleriche\.60.gmail.com. (
                              2023111335; serial
                              10800; refresh
                              3600; retry
                              604800; expire
                              38400 ); minimum
                            IN      NS                              batleforc.fr.
                            IN      NS                              ns3082912.ip-94-23-38.eu.
      maxleriche.net.       3600    CAA                             0 issue "letsencrypt.org"
      maxleriche.net.       600     IN TXT                          "v=spf1 include:_spf.protonmail.ch ~all"
      @                     600     IN TXT                          "protonmail-verification=eb37b2ad8c95b91c0c993bcdb261f33ae27f9cfd"
      @                     600     MX 10                           mail.protonmail.ch.
      @                     600     MX 20                           mailsec.protonmail.ch.
      @                     3600    TXT                             "google-site-verification=i137wbVZIBrHr921ksYBxdfwc32h_iUzHpHgTED0gc4"
      @                     3600    TXT                             "mlab-domain-1ee34955-2171-460e-8883-8bfe2000e7da"
      maxleriche.net.       3600    A                               94.23.38.81
      maxleriche.net.       3600    AAAA                            2001:41d0:2:2751::1
      maxleriche.net.       NS                                      batleforc.fr.
      maxleriche.net.       NS                                      ns3082912.ip-94-23-38.eu.
      beta                  3600    A                               94.23.38.81
      beta                  3600    AAAA                            2001:41d0:2:2751::1
      protonmail._domainkey 3600    CNAME                           protonmail.domainkey.dokpfhrmhsyhdvnrkoythmysqusv3yw6i5wxyt45gziglhzwcfcba.domains.proton.ch.
      protonmail2._domainkey 3600    CNAME                          protonmail2.domainkey.dokpfhrmhsyhdvnrkoythmysqusv3yw6i5wxyt45gziglhzwcfcba.domains.proton.ch.
      protonmail3._domainkey 3600    CNAME                          protonmail3.domainkey.dokpfhrmhsyhdvnrkoythmysqusv3yw6i5wxyt45gziglhzwcfcba.domains.proton.ch.
      _dmarc                 3600    TXT                            "v=DMARC1; p=quarantine"
      _atproto.maxweebo      3600    TXT                            "did=did:plc:omws73kv4dp3inakwy3srhn2

  "38.23.94.in-addr.arpa":
    zone: "38.23.94.in-addr.arpa."
    file: |
      $TTL 1h ;
      $ORIGIN 38.23.94.in-addr.arpa.
      @       IN      SOA     maxleriche.net. maxleriche\.60.gmail.com. (
                              2024011942; serial
                              7200; refresh
                              3600; retry
                              1209600; expire
                              38400 ) ; minimum
      @                   IN      NS                  batleforc.fr.
      @                   IN      NS                  ns3082912.ip-94-23-38.eu.
      81                  IN      PTR                 batleforc.fr.

  "1.5.7.2.2.0.0.0.0.d.1.4.1.0.0.2.ip6.arpa":
    zone: "1.5.7.2.2.0.0.0.0.d.1.4.1.0.0.2.ip6.arpa."
    file: |
      $TTL 1h ;
      $ORIGIN 1.5.7.2.2.0.0.0.0.d.1.4.1.0.0.2.ip6.arpa.
      @       IN      SOA     maxleriche.net. maxleriche\.60.gmail.com. (
                              2026040501; serial
                              7200; refresh
                              3600; retry
                              1209600; expire
                              38400 ) ; minimum
      @                   IN      NS                  batleforc.fr.
      @                   IN      NS                  ns3082912.ip-94-23-38.eu.
      1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0 IN PTR        batleforc.fr.

forwarders:
  - 10.96.0.10
  #- 8.8.8.8
  #- 1.1.1.1

bind9:
  image: ubuntu/bind9
  tag: 9.20-26.04_edge

tsig:
  secretCreatorImage: alpine/k8s:1.35.3
  bind9Image: ubuntu/bind9:9.20-24.10_beta

externalDns:
  version: v0.20.0
  zone: batleforc.fr

httpsNsServeur:
  enabled: false
  nsName: ns.batleforc.fr

annotations:
  metallb.universe.tf/address-pool: one
  metallb.io/ip-allocated-from-pool: one
  metallb.universe.tf/allow-shared-ip: one

blocky:
  enabled: true

repo: ""
