{{- if .Values.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monofolio
  labels:
    app: monofolio
spec:
  selector:
    matchLabels:
      app: monofolio
  template:
    metadata:
      labels:
        app: monofolio
    spec:
      containers:
        - name: monofolio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          pullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

{{- end -}}
