coroot:
  enabled: true
  operator:
    version: "0.9.4"

grafana:
  enabled: true
  version: "12.1.1"
  datasources:
    clickhouse:
      - name: default
        value: jsyy2pqy

repo: ""

monitoringApp:
  enabled: true
