repo: "https://github.com/batleforc/Weebo5GitOps"

dns:
  ns: dns
  enabled: true

ingress:
  enabled: true

traefik:
  ips: ""

storage:
  local:
    enabled: true

vpn:
  enabled: true

db:
  enabled: true
