repo: "https://github.com/batleforc/Weebo5GitOps"

dns:
  ns: dns
  enabled: true

ingress:
  enabled: true

traefik:
  ips: ""

external:
  enabled: true

storage:
  local:
    enabled: true

vault:
  enabled: true

s3:
  enabled: true

vpn:
  enabled: true

db:
  enabled: true

monofolio:
  enabled: true

git:
  enabled: true

registry:
  enabled: true

che:
  enabled: true

guard:
  enabled: true

chat:
  enabled: true
