{{- if .Values.rustfs.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustfs
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: '{{ .Values.repo }}'
    path: '1.helm/rustfs'
    helm:
      releaseName: rustfs
      valuesObject:
        harborAdminPassword: "vault:mv/data/registry/config#HARBOR_ADMIN_PASSWORD"
        podAnnotations:
          vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
          vault.security.banzaicloud.io/vault-role: "default"
          vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
          vault.security.banzaicloud.io/vault-agent: "false"
          vault.security.banzaicloud.io/vault-path: "kubernetes"
        secret:
          rustfs:
            access_key: "vault:mv/data/s3/config#S3_ADMIN_ID"
            secret_key: "vault:mv/data/s3/config#S3_ADMIN_PASSWORD"
        extraEnv:
          - name: RUSTFS_IDENTITY_OPENID_ENABLE
            value: "on"
          - name: RUSTFS_IDENTITY_OPENID_CONFIG_URL
            value: "vault:mv/data/s3/auth#AUTHENTIK_URL"
          - name: RUSTFS_IDENTITY_OPENID_CLIENT_ID
            value: "vault:mv/data/s3/auth#AUTHENTIK_CLIENT_ID"
          - name: RUSTFS_IDENTITY_OPENID_CLIENT_SECRET
            value: "vault:mv/data/s3/auth#AUTHENTIK_CLIENT_SECRET"
          - name: RUSTFS_IDENTITY_OPENID_GROUPS_CLAIM
            value: "groups"
          - name: RUSTFS_IDENTITY_OPENID_ROLES_CLAIM
            value: "roles"
          - name: RUSTFS_IDENTITY_OPENID_REDIRECT_URI
            value: "https://{{ .Values.rustfs.domain.core }}/oauth_callback"
          - name: RUSTFS_IDENTITY_OPENID_SCOPES
            value: "openid,profile,email,groups"
          - name: RUSTFS_IDENTITY_OPENID_DISPLAY_NAME
            value: "Batleforc SSO"
        mode:
          standalone:
            enabled: true
          distributed:
            enabled: false
        ingress:
          className: traefik
          enabled: false
          hosts:
            - host: {{ .Values.rustfs.domain.core }}
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            enabled: true
        ingressAnnotations:
          cert-manager.io/cluster-issuer: "outbound"
        storageclass:
          name: "local-path"
          dataStorageSize: "40Gi"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Release.Namespace }}
{{- end -}}
