tuwunel:
  enabled: true
  baseDomain: "batleforc.fr"
  realDomain: "chat.batleforc.fr"
  image:
    version: "v1.6.1"

repo: ""

elementWeb:
  enabled: true
  domain: "chat-web.batleforc.fr"
  image:
    url: "vectorim/element-web"
    version: "latest"
