certManager:
  enabled: true
  version: 1.20.0
  installCRDs: true
  certIssuer:
    enabled: true
    name: outbound
    email: "maxleriche.60@gmail.com"
  certIssuerDNS01:
    enabled: false
    name: dns-01
    email: "maxleriche.60@gmail.com"
    nameservers: "dns-server-in.dns.svc.cluster.local"
    namespace: "dns"

traefik:
  enabled: true
  version: 39.0.7
  ips: ""
  kubeCRD:
    enabled: true
  kubeIngress:
    enabled: true
  gatewayAPI:
    enabled: false
  middleware:
    ipAllowList:
      sourceRange:
        - 10.244.0.0/16
        - fd00:10:244::/56
        - 10.96.0.0/12
        - fd00:10:96::/112
        - 86.239.204.179/32
        - 2a01:cb18:ccb:aa00:efa0:6903:9a7b:5b5/128

authentik:
  enabled: false

repo: ""

subApp:
  enabled: true
