gitPages:
  enabled: true
  env:
    PAGES_WILDCARD_0_DOMAIN: "git.batleforc.fr"
    PAGES_WILDCARD_0_CLONE_URL: "https://git.batleforc.fr/<user>/<project>.git"
    PAGES_WILDCARD_0_INDEX_REPO: "<user>.git.batleforc.fr"
    PAGES_WILDCARD_0_AUTHORIZATION: "forgejo"
  dnsWildcardDomain:
    enabled: true
    domain: "git.batleforc.fr"
    certificateName: "cert-dns01-git-wildcard"
  middleware:
    enabled: true
    redirectToHttps:
      enabled: true
    strictSource:
      enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
