forgejo:
  enabled: true
  version: "17.1.2"
  dns: "git.batleforc.fr"
  runner:
    enabled: true
    job:
      image: alpine/k8s:1.35.4
  gitPages:
    enabled: true

repo: ""

traefik:
  ips: ""

postgresql:
  enabled: false
