{{- if .Values.forgejo.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sync-waves.argoproj.io/sync-wave: "5"
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: auth
  target:
    name: git-auth
    template:
      type: Opaque
      data:
        key: '{{ printf "{{"}} .client_id }}'
        secret: '{{ printf "{{"}} .client_secret }}'
  data:
    - secretKey: client_id
      remoteRef:
        key: mv/git/auth
        property: AUTHENTIK_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: mv/git/auth
        property: AUTHENTIK_CLIENT_SECRET
{{- end -}}
