{{- if .Values.tuwunel.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tuwunel
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  source:
    chart: conduwuit
    repoURL: {{ .Values.repo }}
    path: '1.helm/tuwunel'
    helm:
      releaseName: tuwunel
      valuesObject:
        server_name: {{ .Values.tuwunel.baseDomain}}
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: outbound
        image:
          repository: ghcr.io/matrix-construct/tuwunel
          tag: {{ .Values.tuwunel.image.version }}
          pullPolicy: Always
        config:
          global:
            new_user_displayname_suffix: "🆕"
            well_known:
              client: "https://{{ .Values.tuwunel.realDomain }}"
              server: "{{ .Values.tuwunel.realDomain }}:443"

  destination:
    name: in-cluster
    namespace: {{ .Release.Namespace }}
{{- end -}}
