apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secret
  namespace: "{{ .Release.Namespace }}"
  annotations:
    sync-waves.argoproj.io/sync-wave: "0"
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h
  secretStoreRef:
    name: auth
  target:
    name: vpn-auth
    template:
      type: Opaque
      data:
        idpClientID: '{{ printf "{{"}} .idpClientID }}'
        idpServiceAccountPassword: '{{ printf "{{"}} .idpServiceAccountPassword }}'
        idpServiceAccountUser: '{{ printf "{{"}} .idpServiceAccountUser }}'
        relayPassword: '{{ printf "{{"}} .relayPassword }}'
        datastoreEncryptionKey: '{{ printf "{{"}} .datastoreEncryptionKey }}'
        authBaseURL: '{{ printf "{{"}} .authBaseURL }}'
        authBase: "https://auth.batleforc.fr"
        oidcConfigEndpoint: '{{ printf "{{"}} .oidcConfigEndpoint }}'
        clientSecret: '{{ printf "{{"}} .clientSecret }}'
  data:
    - secretKey: idpClientID
      remoteRef:
        key: mv/vpn/auth
        property: NETBIRD_AUTH_CLIENT_ID
    - secretKey: idpServiceAccountPassword
      remoteRef:
        key: mv/vpn/auth
        property: NETBIRD_IDP_MGMT_EXTRA_PASSWORD
    - secretKey: idpServiceAccountUser
      remoteRef:
        key: mv/vpn/auth
        property: NETBIRD_IDP_MGMT_EXTRA_USERNAME
    - secretKey: relayPassword
      remoteRef:
        key: mv/vpn/auth
        property: NETBIRD_REPLAY_PASSWORD
    - secretKey: datastoreEncryptionKey
      remoteRef:
        key: mv/vpn/auth
        property: NETBIRD_DATASTORE_ENCRYPTION_KEY
    - secretKey: authBaseURL
      remoteRef:
        key: mv/vpn/auth
        property: NETBIRD_AUTH_BASE_URL
    - secretKey: oidcConfigEndpoint
      remoteRef:
        key: mv/vpn/auth
        property: NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT
    - secretKey: clientSecret
      remoteRef:
        key: mv/vpn/auth
        property: NETBIRD_AUTH_AUDIENCE
