{{- if .Values.netbird.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: '{{ .Values.repo }}'
    path: '1.helm/netbird'
    helm:
      releaseName: netbird
      valuesObject:
        fullnameOverride: netbird
        management:
          image:
            tag: "{{ .Values.netbird.server.version }}"
          configYaml:
            server:
              listenAddress: :80
              exposedAddress: https://{{ .Values.netbird.domain }}:443
              stunPorts: [3478]
              metricsPort: 9090
              healthcheckAddress: :9000
              logLevel: info
              logFile: console
              authSecret: "${NETBIRD_DATASTORE_ENCRYPTION_KEY}"
              dataDir: /var/lib/netbird
              auth:
                issuer: https://{{ .Values.netbird.domain }}/oauth2
                signKeyRefreshEnabled: true
                dashboardRedirectURIs:
                  - https://{{ .Values.netbird.domain }}/nb-auth
                  - https://{{ .Values.netbird.domain }}/nb-silent-auth
                cliRedirectURIs:
                  - http://localhost:53000/
              store:
                engine: "sqlite"  # sqlite, postgres, or mysql
                dsn: ""  # Connection string for postgres or mysql
                encryptionKey: "${NETBIRD_DATASTORE_ENCRYPTION_KEY}"
          persistentVolume:
            enabled: true
          envsubst:
            enabled: true
            envFromSecret:
              NETBIRD_DATASTORE_ENCRYPTION_KEY: vpn-auth/datastoreEncryptionKey
          env:
            NETBIRD_AUTH_PKCE_DISABLE_PROMPT_LOGIN: "true"
            NETBIRD_AUTH_REDIRECT_URI: "/auth"
            NETBIRD_AUTH_SILENT_REDIRECT_URI: "/silent-auth"
            AUTH_SUPPORTED_SCOPES: openid profile email offline_access api
            USE_AUTH0: false
            NETBIRD_MGMT_IDP: "authentik"
          envFromSecret:
            NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT: vpn-auth/oidcConfigEndpoint
            NETBIRD_AUTH_CLIENT_ID: vpn-auth/idpClientID
            NETBIRD_IDP_MGMT_CLIENT_ID: vpn-auth/idpClientID
            NETBIRD_IDP_MGMT_EXTRA_USERNAME: vpn-auth/idpServiceAccountUser
            NETBIRD_IDP_MGMT_EXTRA_PASSWORD: vpn-auth/idpServiceAccountPassword
            NETBIRD_DATASTORE_ENCRYPTION_KEY: vpn-auth/datastoreEncryptionKey
            NETBIRD_AUTH_AUDIENCE: vpn-auth/idpClientID
            NETBIRD_AUTH_DEVICE_AUTH_CLIENT_ID: vpn-auth/idpClientID
            NETBIRD_AUTH_DEVICE_AUTH_AUDIENCE: vpn-auth/idpClientID
            OIDC_CONFIG_ENDPOINT: vpn-auth/oidcConfigEndpoint
            IDP_CLIENT_SECRET: vpn-auth/clientSecret
          serviceStun:
            enabled: true
            type: LoadBalancer
            annotations:
              lbipam.cilium.io/sharing-key: "weebo-gate"
              lbipam.cilium.io/ips: "{{ .Values.traefik.ips }}"
              lbipam.cilium.io/sharing-cross-namespace: "*"

        dashboard:
          image:
            tag: "{{ .Values.netbird.dashboard.version }}"
          enabled: true
          env:
            # Endpoints
            NETBIRD_MGMT_API_ENDPOINT: https://{{ .Values.netbird.domain }}:443
            NETBIRD_MGMT_GRPC_API_ENDPOINT: https://{{ .Values.netbird.domain }}:443
            # OIDC
            NETBIRD_AUTH_PKCE_DISABLE_PROMPT_LOGIN: "true"
            NETBIRD_AUTH_REDIRECT_URI: "/auth"
            NETBIRD_AUTH_SILENT_REDIRECT_URI: "/silent-auth"
            AUTH_SUPPORTED_SCOPES: openid profile email offline_access api
            USE_AUTH0: false
            NETBIRD_MGMT_IDP: "authentik"
          envFromSecret:
            NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT: vpn-auth/oidcConfigEndpoint
            NETBIRD_AUTH_CLIENT_ID: vpn-auth/idpClientID
            NETBIRD_RELAY_AUTH_SECRET: vpn-auth/relayPassword
            NETBIRD_IDP_MGMT_CLIENT_ID: vpn-auth/idpClientID
            NETBIRD_IDP_MGMT_EXTRA_USERNAME: vpn-auth/idpServiceAccountUser
            NETBIRD_IDP_MGMT_EXTRA_PASSWORD: vpn-auth/idpServiceAccountPassword
            NETBIRD_DATASTORE_ENCRYPTION_KEY: vpn-auth/datastoreEncryptionKey
            NETBIRD_AUTH_AUDIENCE: vpn-auth/idpClientID
            NETBIRD_AUTH_DEVICE_AUTH_CLIENT_ID: vpn-auth/idpClientID
            NETBIRD_AUTH_DEVICE_AUTH_AUDIENCE: vpn-auth/idpClientID
            OIDC_CONFIG_ENDPOINT: vpn-auth/oidcConfigEndpoint

        extraManifests:
          - apiVersion: traefik.io/v1alpha1
            kind: IngressRoute
            metadata:
              name: netbird
              labels:
                argocd.argoproj.io/instance: netbird
            spec:
              entryPoints:
                - websecure
              routes:
                - kind: Rule
                  match: Host(`{{ .Values.netbird.domain }}`) && !PathPrefix(`/api`) && !PathPrefix(`/oauth2`) && !PathPrefix(`/ws-proxy/signal`) && !PathPrefix(`/ws-proxy/management`) && !PathPrefix(`/management`) && !PathPrefix(`/signalexchange`) && !PathPrefix(`/relay`)
                  services:
                    - name: netbird-dashboard
                      namespace: vpn
                      passHostHeader: true
                      port: 80
                - kind: Rule
                  match: Host(`{{ .Values.netbird.domain }}`) && PathPrefix(`/api`)
                  services:
                    - name: netbird-management
                      namespace: vpn
                      passHostHeader: true
                      port: 80
                - kind: Rule
                  match: Host(`{{ .Values.netbird.domain }}`) && PathPrefix(`/relay`)
                  services:
                    - name: netbird-management
                      namespace: vpn
                      passHostHeader: true
                      port: 80
                - kind: Rule
                  match: Host(`{{ .Values.netbird.domain }}`) && PathPrefix(`/management`)
                  services:
                    - name: netbird-management
                      namespace: vpn
                      passHostHeader: true
                      port: 80
                      scheme: h2c
                - kind: Rule
                  match: Host(`{{ .Values.netbird.domain }}`) && PathPrefix(`/signalexchange`)
                  services:
                    - name: netbird-management
                      namespace: vpn
                      passHostHeader: true
                      port: 80
                      scheme: h2c
                - kind: Rule
                  match: Host(`{{ .Values.netbird.domain }}`) && PathPrefix(`/ws-proxy/signal`)
                  services:
                    - name: netbird-management
                      namespace: vpn
                      passHostHeader: true
                      port: 80
                - kind: Rule
                  match: Host(`{{ .Values.netbird.domain }}`) && PathPrefix(`/ws-proxy/management`)
                  services:
                    - name: netbird-management
                      namespace: vpn
                      passHostHeader: true
                      port: 80
                - kind: Rule
                  match: Host(`{{ .Values.netbird.domain }}`) && PathPrefix(`/oauth2`)
                  services:
                    - name: netbird-management
                      namespace: vpn
                      passHostHeader: true
                      port: 80
              tls:
                secretName: "vpn-certificate"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vpn

{{- end -}}
