{{- if .Values.netbird.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: '{{ .Values.repo }}'
    path: '1.helm/netbird'
    helm:
      releaseName: netbird
      valuesObject:
        fullnameOverride: netbird
        management:
          image:
            tag: "{{ .Values.netbird.server.version }}"
          configYaml:
            server:
              listenAddress: :80
              exposedAddress: https://{{ .Values.netbird.domain }}:443
              stunPorts: [3478]
              metricsPort: 9090
              healthcheckAddress: :9000
              logLevel: info
              logFile: console
              authSecret: "${NETBIRD_DATASTORE_ENCRYPTION_KEY}"
              dataDir: /var/lib/netbird
              auth:
                issuer: "https://vpn.batleforc.fr/oauth2"
                signKeyRefreshEnabled: true
                dashboardRedirectURIs:
                  - "https://vpn.batleforc.fr/nb-auth"
                  - "https://vpn.batleforc.fr/nb-silent-auth"
                cliRedirectURIs:
                  - "http://localhost:53000/"
              reverseProxy:
                trustedHTTPProxies:
                  - "10.244.0.0/16"
                  - "fd00:10:244::/56"
              store:
                engine: "sqlite"  # sqlite, postgres, or mysql
                dsn: ""  # Connection string for postgres or mysql
                encryptionKey: "${NETBIRD_DATASTORE_ENCRYPTION_KEY}"
          persistentVolume:
            enabled: true
          envsubst:
            enabled: true
            envFromSecret:
              NETBIRD_DATASTORE_ENCRYPTION_KEY: vpn-auth/datastoreEncryptionKey
          serviceStun:
            enabled: true
            type: LoadBalancer
            annotations:
              lbipam.cilium.io/sharing-key: "weebo-gate"
              lbipam.cilium.io/ips: "{{ .Values.traefik.ips }}"
              lbipam.cilium.io/sharing-cross-namespace: "*"

        dashboard:
          image:
            tag: "{{ .Values.netbird.dashboard.version }}"
          enabled: true
          env:
            # Endpoints
            NETBIRD_MGMT_API_ENDPOINT: https://{{ .Values.netbird.domain }}
            NETBIRD_MGMT_GRPC_API_ENDPOINT: https://{{ .Values.netbird.domain }}
            # OIDC - using embedded IdP
            AUTH_AUDIENCE: netbird-dashboard
            AUTH_CLIENT_ID: netbird-dashboard
            AUTH_CLIENT_SECRET:
            AUTH_AUTHORITY: https://{{ .Values.netbird.domain }}/oauth2
            USE_AUTH0: false
            AUTH_SUPPORTED_SCOPES: openid profile email groups
            AUTH_REDIRECT_URI: /nb-auth
            AUTH_SILENT_REDIRECT_URI: /nb-silent-auth
            # SSL
            NGINX_SSL_PORT: 443
            # Letsencrypt
            LETSENCRYPT_DOMAIN: none

        extraManifests:
          - apiVersion: traefik.io/v1alpha1
            kind: ServersTransport
            metadata:
              name: netbird
            spec:
              forwardingTimeouts:
                responseheadertimeout: 0s
                idleconntimeout: 0s
          - apiVersion: traefik.io/v1alpha1
            kind: IngressRoute
            metadata:
              name: netbird
              labels:
                argocd.argoproj.io/instance: netbird
            spec:
              entryPoints:
                - websecure
              routes:
                - kind: Rule
                  match: Host(`{{ .Values.netbird.domain }}`)
                  priority: 1
                  services:
                    - name: netbird-dashboard
                      namespace: vpn
                      passHostHeader: true
                      port: 80
                      serversTransport: netbird
                - kind: Rule
                  match: Host(`{{ .Values.netbird.domain }}`) && (PathPrefix(`/signalexchange.SignalExchange/`) || PathPrefix(`/management.ManagementService/`))
                  priority: 100
                  services:
                    - name: netbird-management
                      namespace: vpn
                      passHostHeader: true
                      port: 80
                      scheme: h2c
                      serversTransport: netbird
                - kind: Rule
                  match: Host(`{{ .Values.netbird.domain }}`) && (PathPrefix(`/relay`) || PathPrefix(`/ws-proxy/`) || PathPrefix(`/api`) || PathPrefix(`/oauth2`))
                  priority: 100
                  services:
                    - name: netbird-management
                      namespace: vpn
                      passHostHeader: true
                      port: 80
                      serversTransport: netbird
              tls:
                secretName: "vpn-certificate"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vpn

{{- end -}}
