{{- if .Values.blocky.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |-
    {{- .Values.blocky.config | toYaml | nindent 4 }}
{{- end -}}
