{{- if .Values.blocky.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocky-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    coroot.io/monitor: "true"
    coroot.io/port: "4000"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocky
  template:
    metadata:
      annotations:
        checksum/config: '{{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}'
      labels:
        app: blocky
    spec:
      containers:
        - name: blocky
          image: "{{ .Values.blocky.image.repository }}:{{ .Values.blocky.image.tag }}"
          resources:
            limits:
              cpu: {{ .Values.blocky.resources.limits.cpu }}
              memory: {{ .Values.blocky.resources.limits.memory }}
            requests:
              cpu: {{ .Values.blocky.resources.requests.cpu }}
              memory: {{ .Values.blocky.resources.requests.memory }}
          ports:
            {{- range .Values.blocky.service.port }}
            - containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          args:
            - "--config=/config/blocky/config.yml"
          volumeMounts:
            - name: config
              mountPath: /config/blocky
          readinessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
      volumes:
        - name: config
          configMap:
            name: blocky-{{ .Release.Name }}
{{- end -}}
