{{- if .Values.netbird.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "exit-node-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "exit-node-{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "exit-node-{{ .Release.Name }}"
      annotations:
{{- with .Values.netbird.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: exit-node
          {{- if .Values.netbird.adminMode.enabled }}
          image: "{{ .Values.netbird.adminMode.image }}:{{ .Values.netbird.adminMode.version }}"
          imagePullPolicy: {{ .Values.netbird.adminMode.pullPolicy }}
          securityContext:
            capabilities:
              {{- range .Values.netbird.adminMode.capabilities }}
              - {{ . }}
              {{- end }}
          {{- else }}
          image: "{{ .Values.netbird.image }}:{{ .Values.netbird.version }}"
          imagePullPolicy: {{ .Values.netbird.pullPolicy }}
          {{- end }}
          env:
            - name: NB_SETUP_KEY
              value: "{{ tpl .Values.netbird.setup_key . }}" # replace with your setup key
            - name: NETBIRD_PEER_NAME
              value: "{{ .Values.netbird.peer_name }}"
            - name: NB_LOG_LEVEL
              value: "info"
            - name: NETBIRD_URL
              value: "{{ .Values.netbird.url }}"
            - name: TZ
              value: "{{ .Values.netbird.tz }}"
          resources:
{{- with .Values.netbird.resources }}
{{ toYaml . | indent 12 }}
{{- end }}
{{- end -}}
