{{- if and .Values.forgejo.enabled .Values.forgejo.runner.enabled -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-runner-secret
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
        - name: create-runner-secret
          image: {{ .Values.forgejo.runner.job.image }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "=== Starting Forgejo runner secret creation ==="
              echo "Checking for existing runner secret..."
              if kubectl get secret forgejo-runner-secret -n {{ .Release.Namespace }} 2>/dev/null; then
                echo "Runner secret already exists. Skipping creation."
                exit 0
              fi
              echo "Generating token for Forgejo runner, 40 characters long hexadecimal string..."
              TOKEN=$(head -c 20 /dev/urandom | xxd -p)
              echo "Registering runner with Forgejo using the generated token..."
              uuid=$(kubectl exec -n {{ .Release.Namespace }} -c forgejo deploy/forgejo -- forgejo forgejo-cli actions register --name k8s-runner --secret $TOKEN)
              echo "Creating runner secret for Forgejo..."
              kubectl create secret generic forgejo-runner-secret \
                --from-literal=token=$TOKEN \
                --from-literal=uuid=$uuid \
                -n {{ .Release.Namespace }}
              echo "=== Forgejo runner secret creation completed ==="
      restartPolicy: OnFailure
      backoffLimit: 3
{{- end -}}
