{{- if and .Values.forgejo.enabled .Values.forgejo.runner.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forgejo-runner-job
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forgejo-runner-job
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forgejo-runner-job
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: forgejo-runner-job
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: forgejo-runner-job
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
