{{ if and .Values.forgejo.enabled .Values.forgejo.runner.enabled }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ .Release.Name }}-collector
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: auth
      kind: SecretStore
  selector:
    secret:
      name: forgejo-runner-secret
  data:
    - match:
        secretKey: uuid
        remoteRef:
          remoteKey: forgejo-action/sub
          property: uuid
    - match:
        secretKey: token
        remoteRef:
          remoteKey: forgejo-action/sub
          property: token
{{ end }}
