{{- if .Values.vaultwarden.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
  source:
    chart: vaultwarden
    repoURL: https://guerzon.github.io/vaultwarden
    targetRevision: {{ .Values.vaultwarden.version }}
    helm:
      releaseName: vaultwarden
      valuesObject:
        domain: "https://{{ .Values.vaultwarden.domain }}"
        database:
          type: postgresql
          existingSecret: vaultwarden-postgresql-app
          existingSecretKey: uri
        ingress:
          enabled: true
          tlsSecret: vaultwarden-tls
          hostname: {{ .Values.vaultwarden.domain }}
          class: traefik
        image:
          extraVars:
            - key: SSO_ENABLED
              value: true
            - key: SSO_AUTHORITY
              value: "vault:mv/data/{{.Release.Namespace}}/auth#AUTHENTIK_URL"
            - key: SSO_CLIENT_ID
              value: "vault:mv/data/{{.Release.Namespace}}/auth#AUTHENTIK_CLIENT_ID"
            - key: SSO_CLIENT_SECRET
              value: "vault:mv/data/{{.Release.Namespace}}/auth#AUTHENTIK_CLIENT_SECRET"
            - key: SSO_SCOPES
              value: email openid profile offline_access
            - key: SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION
              value: false
            - key: SSO_CLIENT_CACHE_EXPIRATION
              value: 0
            - key: SSO_ONLY
              value: true # Set to true to disable email+master password login and require SSO
            - key: SSO_SIGNUPS_MATCH_EMAIL
              value: true
        podAnnotations:
          vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
          vault.security.banzaicloud.io/vault-role: "auth-read"
          vault.security.banzaicloud.io/vault-path: "kubernetes"
          vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
{{- end -}}
