apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "gtfo"
spec:
  endpointSelector: {}
  ingressDeny:
  - fromCIDR:
    - 193.38.250.0/24 # Red machin choses
    - 45.200.148.0/23 # Mario Networks Limited
    - 109.205.213.0/24 # IS-AS-1
    - 47.236.0.0/17 # Alibaba
    - 8.222.0.0/15 # Alibaba - singapore
    - 47.251.0.0/17 # Alibaba - US
    - 47.250.128.0/17 # Alibaba - Malaysia
    - 8.218.0.0/15 # Alibaba - Singapore 2
    - 47.254.0.0/16 # Alibaba - US 2
    - 47.84.0.0/15 # Alibaba - Singapore 3
    - 8.152.0.0/14 # Hangzhou Alibaba Advertising Co.,Ltd. - China
    - 158.220.96.0/19 # Contabo - Germany
    - 81.161.238.0/24 # Nybula - Bulgaria
    - 196.189.0.0/17 # Ethiopian Telecommunication Corporation - Ethiopia
    - 78.153.140.0/24 # HostGlobal plus - UK
    - 154.216.20.0/24 # Silent Connection - Lithuania
    - 192.250.228.163/32 # WHG Hosting Service - Singapore
    - 116.140.0.0/14 # China Unicom China 169 Backbone - China
    - 196.112.0.0/12 # ASMedi - Marocco
    - 185.196.8.0/22 # Global Data System IT - UK
    - 185.196.220.0/24 # ColocationX Ltd - USA
    - 213.152.176.0/23 # GlobalLayer B.V. - Netherlands
    - 213.232.86.0/23 # PacketHub SA - Netherlands
    - 94.156.177.0/24 # Railnet LLC - Bulgaria
    - 87.120.126.0/23 # Ekabi
    - 104.248.0.0/16 # Digital Ocean - US
    - 194.50.16.0/24 # Alsycon B.V - Netherlands
    - 152.32.128.0/18 # UCLOUD - Hong Kong
    - 170.39.218.0/24 # Fbw Networks SAS - France
    - 52.208.0.0/13 # Amazon-02 - Ireland
    - 39.100.0.0/14 # Alibaba - China
    - 120.224.0.0/15 # Shandong Mobile Communication Company Limited - China
    - 94.156.166.0/23 # CheapyHost - Bulgaria
    - 47.79.0.0/17 # Alibaba - Japan
    - 36.213.196.0/22 # China Mobile - China
    - 103.232.120.0/22 # Viet solutions - Vietnam
    - 92.246.140.0/22 # Dpkgsoft - Germany
    - 161.97.160.0/20 # Contabo - Germany
    - 103.123.44.0/22 # Unigro - India
    - 181.37.240.89/32
    - 206.166.251.193/32
    - 213.210.60.58/32
  ingress:
  - fromEntities:
    - "all"
