apiVersion: v1
kind: ConfigMap
metadata:
  name: named-map
  namespace: "{{ .Release.Namespace }}"
data:
  named.conf: |
    include "/val/lib/bind/pri/tsig.key";
    {{- if .Values.httpsNsServeur.enabled }}
    tls local-tls {
      key-file "/var/lib/bind/pri/ns-server-tls/tls.key";
      cert-file "/var/lib/bind/pri/ns-server-tls/tls.crt";
    };
    {{- end }}
    options {
      directory "/var/cache/bind";
      querylog yes;
      listen-on port 53 { any; };
      listen-on-v6 port 53 { any; };
      {{- if .Values.httpsNsServeur.enabled }}
      listen-on port 443 tls local-tls http default {any;};
      listen-on-v6 port 443 tls local-tls http default {any;};
      {{- end }}

      allow-query { any; };
      allow-recursion {
        none;
      };
      allow-transfer {
        none;
      };
      allow-update {
        none;
      };
    };
    {{ range $key, $value := .Values.zone }}
    zone "{{ $value.zone }}" {
      type primary;
      file "/var/lib/bind/pri/{{$value.zone}}/{{ $key}}";
      allow-transfer {
        key "tsig-key";
      };
      update-policy {
        grant tsig-key zonesub ANY;
      };
    };
    {{ end }}
