{{if .Values.httpsNsServeur.enabled}}
## IngressRouteTCP for ns.batleforc.fr
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ns-server
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`{{ .Values.httpsNsServeur.nsName }}`)
      services:
        - name: dns-server-https
          namespace: "{{ .Release.Namespace }}"
          port: 443
  tls:
    passthrough: true

{{end}}
