certManager:
  enabled: true
  version: 1.20.0
  installCRDs: true
  certIssuer:
    enabled: true
    name: outbound
    email: "maxleriche.60@gmail.com"
  certIssuerDNS01:
    enabled: true
    name: dns-01
    email: "maxleriche.60@gmail.com"
    nameservers: "dns-server-in.dns.svc.cluster.local"
    namespace: "dns"

traefik:
  enabled: true
  version: 40.3.0
  ips: ""
  kubeCRD:
    enabled: true
  kubeIngress:
    enabled: true
  gatewayAPI:
    enabled: false
  plugins:
    bouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.6.0"

authentik:
  enabled: false

rybbit:
  enabled: false
  dns: "track.batleforc.fr"
  disableSignup: true
  additionalDomain:
    - name: "maxleriche.net"
      certName: "maxleriche-net-certificate"

repo: ""

subApp:
  enabled: true
