{{- if .Values.harbor.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    chart: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: {{ .Values.harbor.version }}
    helm:
      releaseName: harbor
      valuesObject:
        harborAdminPassword: "vault:mv/data/registry/config#HARBOR_ADMIN_PASSWORD"
        portal:
          automountServiceAccountToken: true
        core:
          automountServiceAccountToken: true
          podAnnotations:
            inject-certs: "enabled"
            vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
            vault.security.banzaicloud.io/vault-role: "auth-read"
            vault.security.banzaicloud.io/vault-path: "kubernetes"
            vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
            coroot.com/scrape-metrics: 'true'
            coroot.com/metrics-port: '8001'
        jobservice:
          automountServiceAccountToken: true
          podAnnotations:
            coroot.com/scrape-metrics: 'true'
            coroot.com/metrics-port: '8001'
        registry:
          automountServiceAccountToken: true
          podAnnotations:
            coroot.com/scrape-metrics: 'true'
            coroot.com/metrics-port: '8001'
        exporter:
          automountServiceAccountToken: true
          podAnnotations:
            inject-certs: "enabled"
            vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
            vault.security.banzaicloud.io/vault-role: "auth-read"
            vault.security.banzaicloud.io/vault-path: "kubernetes"
            vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
            coroot.com/scrape-metrics: 'true'
            coroot.com/metrics-port: '8001'
        metrics:
          enabled: true
          serviceMonitor:
            enabled: false
        externalURL: https://{{ .Values.harbor.domain.core }}
        persistence:
          persistentVolumeClaim:
            registry:
              size: 50Gi
        expose:
          tls:
            certSource: secret
            secret:
              secretName: harbor-tls
              notarySecretName: notary-harbor-tls
          ingress:
            enabled: true
            controller: traefik
            annotations:
              kubernetes.io/ingress.class: "traefik"
              cert-manager.io/cluster-issuer: "outbound"
            hosts:
              core: {{ .Values.harbor.domain.core }}
              notary: {{ .Values.harbor.domain.notary }}
        trivy:
          automountServiceAccountToken: true
          podAnnotations:
            vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
            vault.security.banzaicloud.io/vault-role: "default"
            vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
            vault.security.banzaicloud.io/vault-agent: "false"
            vault.security.banzaicloud.io/vault-path: "kubernetes"
          # gitHubToken: vault:secret/data/backstage/env#github_token
        database:
          type: external
          external:
            host: harbor-postgresql-rw
            port: 5432
            username: postgres
            existingSecret: harbor-postgresql-superuser
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Release.Namespace }}
  ignoreDifferences:
  - group: ''
    kind: Secret
    name: harbor-core
    namespace: {{ .Release.Namespace }}
    jsonPointers:
    - /data/CSRF_KEY
    - /data/secret
    - /data/tls.crt
    - /data/tls.key
  - group: ''
    kind: Secret
    name: harbor-jobservice
    namespace: {{ .Release.Namespace }}
    jsonPointers:
    - /data/JOBSERVICE_SECRET
  - group: ''
    kind: Secret
    name: harbor-registry
    namespace: {{ .Release.Namespace }}
    jsonPointers:
    - /data/REGISTRY_HTTP_SECRET
  - group: ''
    kind: Secret
    name: harbor-registry-htpasswd
    namespace: {{ .Release.Namespace }}
    jsonPointers:
    - /data/REGISTRY_HTPASSWD
  - group: 'apps'
    kind: Deployment
    name: harbor-core
    namespace: {{ .Release.Namespace }}
    jsonPointers:
    - /spec/template/metadata/annotations
  - group: 'apps'
    kind: Deployment
    name: harbor-jobservice
    namespace: {{ .Release.Namespace }}
    jsonPointers:
    - /spec/template/metadata/annotations
  - group: 'apps'
    kind: Deployment
    name: harbor-registry
    namespace: {{ .Release.Namespace }}
    jsonPointers:
    - /spec/template/metadata/annotations
{{- end -}}
