{{- if .Values.monofolio.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monofolio-project
  namespace: argocd
spec:
  roles:
    - name: pipelines
      description: forgejo pipelines role
      policies:
        # Allow pipelines to sync applications in the project
        - p, repo:batleforc/monofolio-rs:ref:refs/heads/main, applications, sync, monofolio-project/monofolio, allow
        - p, repo:batleforc/monofolio-rs:ref:refs/heads/main, applications, get, monofolio-project/monofolio, allow
  sourceRepos:
    - '{{ .Values.repo }}'
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: 'monofolio'
  clusterResourceWhitelist:
    - group: ''
      kind: 'Namespace'
{{- end -}}
