kaniop:
  enabled: false
  version: 0.5.7
  instanceName: batleforc-kaniop

authentik:
  enabled: true
  version: 2026.2.1

dns:
  domain: auth.batleforc.fr
  certificate:
    enabled: true
    name: auth-tls
    issuerRef: "outbound"
    issuerRefKind: ClusterIssuer
  createWithCRD: false
  ipv4:
    enabled: true
    addresses:
      - ""
  ipv6:
    enabled: true
    addresses:
      - ""
